# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-12 09:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('postal_code', models.CharField(max_length=20, verbose_name='Postal_code')),
                ('city', models.CharField(max_length=255, verbose_name='City')),
                ('country', models.CharField(choices=[('NL', 'Netherlands'), ('DE', 'Germany'), ('BE', 'Belgium')], max_length=100, verbose_name='Country')),
            ],
            options={
                'verbose_name': 'Address',
            },
        ),
        migrations.CreateModel(
            name='DayOpeningHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_first', models.TimeField(blank=True, null=True)),
                ('close_first', models.TimeField(blank=True, null=True)),
                ('open_second', models.TimeField(blank=True, null=True)),
                ('close_second', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('order', models.IntegerField(default=9999, help_text='The order this organization will be displayed in the category. Organizations without this value will be ordered randomly.', verbose_name='Order')),
                ('phone_nr', models.CharField(max_length=30, verbose_name='Phone number')),
                ('website', models.URLField(blank=True, help_text='Example: http://mywebsite.com or https://www.mywebsite.com', null=True, verbose_name='Website')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('update_opening_hours_daily', models.BooleanField(default=False, verbose_name='Update opening hours daily')),
                ('is_active', models.BooleanField(default=True, help_text='Show the organization on the website', verbose_name='Active')),
                ('is_approved', models.BooleanField(default=False, help_text='The organization should be approved by the website administrator,If approved, the organization will be shown on the website.', verbose_name='Approved')),
                ('is_blocked', models.BooleanField(default=False, help_text='Organization is blocked and will not be shown on the website', verbose_name='Blocked')),
                ('is_member', models.BooleanField(default=True, help_text='Is the organization a member', verbose_name='Member')),
                ('rooms_available', models.BooleanField(default=False, help_text='Are there currently rooms available?', verbose_name='Rooms available')),
            ],
            options={
                'verbose_name': 'Organization',
            },
        ),
        migrations.CreateModel(
            name='OrganizationCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('rooms_available_applies', models.BooleanField(default=False, help_text='Does rooms available apply to this organization category?', verbose_name='Rooms available')),
            ],
            options={
                'verbose_name': 'Organization Category',
                'verbose_name_plural': 'Organization categories',
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organizations', to='organizations.OrganizationCategory', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='organization',
            name='fri',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_fri', to='organizations.DayOpeningHours', verbose_name='Friday'),
        ),
        migrations.AddField(
            model_name='organization',
            name='mon',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_mon', to='organizations.DayOpeningHours', verbose_name='Monday'),
        ),
        migrations.AddField(
            model_name='organization',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AddField(
            model_name='organization',
            name='sat',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_sat', to='organizations.DayOpeningHours', verbose_name='Saturday'),
        ),
        migrations.AddField(
            model_name='organization',
            name='sun',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_sun', to='organizations.DayOpeningHours', verbose_name='Sunday'),
        ),
        migrations.AddField(
            model_name='organization',
            name='thu',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_thu', to='organizations.DayOpeningHours', verbose_name='Thursday'),
        ),
        migrations.AddField(
            model_name='organization',
            name='today',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.DayOpeningHours', verbose_name='Today'),
        ),
        migrations.AddField(
            model_name='organization',
            name='tue',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_tue', to='organizations.DayOpeningHours', verbose_name='Tuesday'),
        ),
        migrations.AddField(
            model_name='organization',
            name='wed',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_wed', to='organizations.DayOpeningHours', verbose_name='Wednesday'),
        ),
        migrations.AddField(
            model_name='address',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='organizations.Organization'),
        ),
    ]
